-- Criação das tabelas

-- Tabela CUSTOMERS
CREATE TABLE CUSTOMERS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME VARCHAR(128) NOT NULL,
   LASTNAME VARCHAR(155) NOT NULL,
   PHONE VARCHAR(16) NOT NULL,
   EMAIL VARCHAR(32) NOT NULL,
   ADDRESS VARCHAR(200) NOT NULL,
   CITY VARCHAR(64) NOT NULL,
   STATE VARCHAR(2) NOT NULL,
   BIRTH_DATE DATETIME
);

-- Criando a tabela CAR_MODELS
CREATE TABLE CAR_MODELS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   MODEL_NAME VARCHAR(120) NOT NULL
);

-- Criando a tabela CAR_BRANDS
CREATE TABLE CAR_BRANDS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   BRAND_NAME VARCHAR(32) NOT NULL
);

-- Criando a tabela CARS
CREATE TABLE CARS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME VARCHAR(120) NOT NULL,
   YEAR INTEGER NOT NULL,
   COLOR VARCHAR(32) NOT NULL,
   KM FLOAT(10,2) NOT NULL,
   STATUS VARCHAR(17) NOT NULL,
   BRAND_ID INTEGER NOT NULL,
   MODEL_ID INTEGER NOT NULL,

   FOREIGN KEY (MODEL_ID) REFERENCES CARS_MODELS (ID)
);

-- Criando a tabela POSITIONS
CREATE TABLE POSITIONS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   DESCRIPTION VARCHAR(120) NOT NULL
);

-- Criando a tabela EMPLOYEES
CREATE TABLE EMPLOYEES (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME VARCHAR(100) NOT NULL,
   PHONE VARCHAR(16) NOT NULL,
   CONTRACT_DATE DATETIME,
   POSITION_ID INTEGER NOT NULL,

   FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID)
);


-- Criando a tabela LOCATIONS
-- FAZ REFERÊNCIAS À CUSTOMERS, CARS, EMPLOYEES

CREATE TABLE LOCATIONS (
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   START_DATE DATETIME NOT NULL,
   END_DATE DATETIME NOT NULL,
   TOTAL FLOAT(10,2) NOT NULL,
   CUSTOMER_ID INTEGER NOT NULL,
   CAR_ID INTEGER NOT NULL,
   EMPLOYEE_ID INTEGER NOT NULL,

   FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
   FOREIGN KEY (CAR_ID) REFERENCES CARS (ID),
   FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);
